import{a,i as f}from"./assets/vendor-ae0cc531.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function u(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerpolicy&&(r.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?r.credentials="include":t.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(t){if(t.ep)return;t.ep=!0;const r=u(t);fetch(t.href,r)}})();a.defaults.headers.common["x-api-key"]="live_KjUOTxpouYppo9Ng5UJyamdaD8xBhIN3LJWEJA1FyX6VZH6DnC2BhI0Cgoy0gAot";function m(){return a.get("https://api.thecatapi.com/v1/breeds")}function p(e){const o=new URLSearchParams({breed_ids:e});return a.get(`https://api.thecatapi.com/v1/images/search?${o}`)}const n={breedsList:document.querySelector(".breed-select"),loader:document.querySelector(".loader"),catInfo:document.querySelector("div.cat-info")};g();n.breedsList.addEventListener("change",h);function h(e){y(e.target.value)}function y(e){d(),n.catInfo.innerHTML="",p(e).then(({data:[o]})=>{n.catInfo.innerHTML=L(o),i()}).catch(o=>{i(),l(o)})}function g(){d(),m().then(({data:e})=>{n.breedsList.innerHTML=e.map(o=>`<option value="${o.id}">${o.name}</option>`).join(""),i(),n.breedsList.classList.remove("visually-hidden")}).catch(e=>{i(),l(e)})}function L(e){return`<div class="cat-info-card">
            <img class="cat-info-image" src="${e.url}" alt="cat" />
            <div class="cat-info-holder">
              <h2 class="cat-info-title">${e.breeds[0].name}</h2>
              <p class="cat-info-text">${e.breeds[0].description}</p>
              <p class="cat-info-text"><b>Temperament:</b> ${e.breeds[0].temperament}</p>
            </div>
          </div>`}function d(){n.loader.classList.remove("visually-hidden")}function i(){n.loader.classList.add("visually-hidden")}function l(e){f.show({color:"red",title:"Ooops! error occured",message:`${e.name}: ${e.message}`,position:"topRight"})}
//# sourceMappingURL=commonHelpers.js.map
